# Generated by Django 3.2.3 on 2021-05-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('emailPrivate', models.CharField(max_length=100)),
                ('emailPublic', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='foo',
        ),
        migrations.AddField(
            model_name='shelves',
            name='users_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.users'),
        ),
    ]
