# Generated by Django 3.2.3 on 2021-05-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0007_alter_shelves_users_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
